tms/tms/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('todo.urls')),
    path('admin/', admin.site.urls), # Keep
    path('accounts/', include('django.contrib.auth.urls')),
]

tms/todo/urls.py
from django.urls import path

from .views import Create, Index, Details, Update, Delete
from . import views

app_name = 'todo'
urlpatterns = [
    path('', Index.as_view(), name='items'),
    path('create/', Create, name='create'),
    path('<int:pk>', Details.as_view(), name='detail'),
    path('<int:pk>/update/', Update.as_view(), name='update'),
    path('<int:pk>/delete/', Delete.as_view(), name='delete'),
    path('<int:pk>/toggle/', 
        views.Togglebool.as_view(), name='toggle'),
]

tms/todo/models.py
from django.db import models

# Create your models here.


class Task(models.Model):
    task = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    desc = models.TextField(max_length=200, null=True)
    done = models.BooleanField(default=False)
    objects = None

    def __str__(self):
        return(self.task)

tms/todo/forms.py
from django.forms import ModelForm
from todo.models import Task


# Create the form class.
class TodoForm(ModelForm):
    class Meta:
        model = Task
        fields = ['task','desc']

tms/todo/views.py
from django.views.decorators.csrf import csrf_exempt
from django.db.utils import IntegrityError
from django.utils.decorators import method_decorator
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, CreateView, DeleteView, DetailView, UpdateView, View
from django.urls import reverse_lazy
from django.http import HttpResponse
# Create your views here.
from .models import Task
from todo.forms import TodoForm

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q


class Index(ListView):
    model = Task

    def get(self, request):
        strval = request.GET.get("search", False)
        if strval:
            # Simple title-only search
            # objects = Task.objects.filter(title__contains=strval).select_related().order_by('-updated_at')[:10]

            # Multi-field search
            query = Q(task__contains=strval)
            items = Task.objects.filter(query).select_related()
        else:
            # try both versions with > 4 posts and watch the queries that happen
            items = Task.objects.all()
            # objects = Task.objects.select_related().all().order_by('-updated_at')[:10]
    # template_name = 'todo/todo_index.html'

    # def get(self, request):
    #     # items = Task.objects.all().count()
    #     items = Task.objects.all()

        ctx = {'task_list': items}
        return render(request, 'todo/task_list.html', ctx)


class Details(LoginRequiredMixin, DetailView):
    model = Task
    # template_name = 'todo/todo_details.html'

    # def get(self, request, pk):
    #     item = Task.objects.get(id=pk)
    #     context = {'item': item}
    #     return render(request, self.template_name, context)


def Create(request):
    form = TodoForm(request.POST)
    form.save()
    return HttpResponse()


class Update(LoginRequiredMixin, UpdateView):
    model = Task
    template = 'todo/task_update.html'
    success_url = reverse_lazy('blog:home')

    def get(self, request, pk):
        task = get_object_or_404(self.model, pk=pk)
        # print(blog.title)
        ctx = {'task': task.task, 'desc': task.desc}
        # print(ctx)
        return render(request, self.template, ctx)

    def post(self, request, pk):
        task = get_object_or_404(self.model, pk=pk)
        form = TodoForm(request.POST, instance=blog)
        if not form.is_valid():
            ctx = {'task': task.name, 'desc': task.desc}
            return render(request, self.template, ctx)

        form.save()
        return redirect(self.success_url)
    success_url = reverse_lazy('todo:items')


class Delete(LoginRequiredMixin, DeleteView):
    model = Task
    fields = ['task', 'desc']
    success_url = reverse_lazy('todo:items')


@method_decorator(csrf_exempt, name='dispatch')
class Togglebool(LoginRequiredMixin, View):
    def post(self, request, pk):
        print("Add PK", pk)
        t = get_object_or_404(Task, id=pk)
        t.done = not t.done
        try:
            print("hello")
            t.save()  # In case of duplicate key
        except IntegrityError as e:
            pass
        return HttpResponse()

# class Create(CreateView):
#     template_name = 'todo/todo_form.html'
#     success_url = reverse_lazy('todo:items')

#     def get(self, request):
#         form = TodoForm()
#         ctx = {'form': form}
#         return render(request, self.template_name, ctx)

#     def post(self, request):
#         form = TodoForm(request.POST)
#         if not form.is_valid():
#             ctx = {'form': form}
#             return render(request, self.template_name, ctx)

#         todo = form.save()
#         return redirect(self.success_url)
    # def get_object(self):

tms/todo/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://bootswatch.com/4/lux/bootstrap.min.css">
    <title>TODO</title>
    <style>
        #line1 {
            display: inline-block;
        }

        #line2 {
            display: inline-block;
        }
    </style>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/ui-lightness/jquery-ui.css"
        crossorigin="anonymous">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js" crossorigin="anonymous"></script>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">

            <a class="navbar-brand" href="#">To Do App</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav ml-auto">

                    <div style="padding-top: 2%">
                        <form action="{% url 'todo:items' %}">
                            <a href="{% url 'todo:items' %}"><svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-arrow-left-circle"
                                    fill="white" xmlns="http://www.w3.org/2000/svg">
                                    <path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
                                    <path fill-rule="evenodd"
                                        d="M12 8a.5.5 0 0 1-.5.5H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5a.5.5 0 0 1 .5.5z" />
                                </svg></i></a>
                            <input type="text" placeholder="Search.." name="search" {% if search %} value="{{ search }}"
                                {% endif %}>
                            <button type="submit"><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-search"
                                    fill="green" xmlns="http://www.w3.org/2000/svg">
                                    <path fill-rule="evenodd"
                                        d="M10.442 10.442a1 1 0 0 1 1.415 0l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1 1 0 0 1 0-1.415z" />
                                    <path fill-rule="evenodd"
                                        d="M6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11zM13 6.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0z" />
                                </svg></button>&nbsp;&nbsp;
                            
                        </form>
                    </div>
                    <a class="nav-link active" href="{% url 'todo:items' %}">Home<span
                            class="sr-only">(current)</span></a>
                    {% if user.is_authenticated %}
                    <a class="nav-link active" href="{% url 'logout' %}?next=/">Logout</a>
                    {% else %}
                    <a class="nav-link active" href="{% url 'login' %}?next=/">Login</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
    <div class="container">
        {% block content %} {% endblock %}
    </div>
</body>

</html>

tms/todo/templates/todo/task_confirm_delete.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<style>
    body {
        background: url("{% static 'todo/delete.jpg' %}") no-repeat center center fixed;
        background-size: cover;

        /* background-image: url("{% static 'todo/list.jpg' %}");
        background-repeat: no-repeat; */
    }
</style>

<body>

    <h1>Delete Task</h1>

    <p>Are you sure you want to delete the task: {{ task }}?</p>

    <form action="" method="POST">
        {% csrf_token %}
        <button class="btn btn-danger" type="submit">Yes, delete</button>
    </form>
</body>
{% endblock %}

tms/todo/templates/todo/task_detail.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<style>
    body {
        background: url("{% static 'todo/detail.jpg' %}") no-repeat center center fixed;
        background-size: cover;

        /* background-image: url("{% static 'todo/list.jpg' %}");
        background-repeat: no-repeat; */
    }
</style>

<body>

    <h1> {{task.task}} </h1><br>
    <h3> {{task.desc}} </h3><br>
    <a class="btn btn-primary" href=" {% url 'todo:update' task.id %} ">Edit task</a>&nbsp;
    <a class="btn btn-danger" href=" {% url 'todo:delete' task.id %} ">Delete task</a><br><br>
    <a class="btn btn-primary" href=" {% url 'todo:items' %} ">Back to all tasks</a><br><br>
</body>
{% endblock %}

tms/todo/templates/todo/task_form.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<style>
    body {
        background: url("{% static 'todo/create.jpg' %}") no-repeat center center fixed;
        background-size: cover;

        /* background-image: url("{% static 'todo/list.jpg' %}");
        background-repeat: no-repeat; */
    }
</style>

<body>

    <div class="continer">

        <form method="POST">
            {% csrf_token %}
            <br>
            <h1>Add New Task</h1>
            <hr>
            <p>Task</p>
            <input type="text" class="form-control" name="task">
            <br>
            <p>Content</p>
            <textarea class="form-control" name="desc"> </textarea>
            <br>
            <button type="submit" class="btn btn-success">Add Task</button>
            <input type="submit" onclick="window.location='{% url 'todo:items' %}' ; return false;" value="Cancel">
        </form>
    </div>
</body>
{% endblock %}

tms/todo/templates/todo/task_list.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<style>
    body {
        background: url("{% static 'todo/todo.jpg' %}") no-repeat center center fixed;
        background-size: cover;

        /* background-image: url("{% static 'todo/list.jpg' %}");
        background-repeat: no-repeat; */
    }

    #myDIV {
        display: none;
    }
</style>

<script>
    function favPost(url) {
            console.log('Requesting JSON');
            $.post(url, {}, function (rowz) {
                console.log(url, 'finished');
                location.reload(true);
            }).fail(function (xhr) {
                alert('Url failed with ' + xhr.status + ' ' + url);
            });


        }

        function myFunction() {
            var x = document.getElementById("myDIV");
            if (x.style.display === "none") {
                x.style.display = "block";
            } else {
                x.style.display = "none";
            }
        }

        function Submitform() {
            var x = document.getElementById("myForm").elements[0].value;
            var y = document.getElementById("myForm").elements[1].value;
            console.log(x)
            $.post("/create/", {
                task: x,
                desc: y,
                csrfmiddlewaretoken: '{{csrf_token}}'
            }, function (rowz) {
                console.log('finished');
                location.reload(true);
            }).fail(function (xhr) {
                alert('Url failed with ' + xhr.status + ' ' + url);
            });


        }

</script>

<body>

    {% if user.is_authenticated %}
    <div class="container">
        <br><br>
        <h2>Todo List</h2>
        {% if task_list %}
        <ul id="list">
            {% for item in task_list reversed %}
            {% if item.done == False %}
            <div id=line1
                style=" display: flex;width: 85%;   font-size: 18px;border-color: rgb(16, 16, 17); border-width: 1px;border-style: solid; ">
                <div style="float: left;width: 80%;padding-right:30px;padding-left:30px;">
                    <a href="#" onclick="favPost('{% url 'todo:toggle' item.id %}',); return false;"
                        style="padding-right:30px;padding-left:30px;"> <svg width="1em" height="1em" viewBox="0 0 16 16"
                            class="bi bi-check-circle" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd"
                                d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
                            <path fill-rule="evenodd"
                                d="M10.97 4.97a.75.75 0 0 1 1.071 1.05l-3.992 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.236.236 0 0 1 .02-.022z" />
                        </svg></a>
                    <a href="{% url 'todo:detail' item.id %}">{{ item.task }}</a>
                </div>
                <div>
                    <a href="{% url 'todo:update' item.id %}"
                        style="padding-right:15px;padding-left:15px; color: turquoise;"><svg width="1em" height="1em"
                            viewBox="0 0 16 16" class="bi bi-pencil-square" fill="currentColor"
                            xmlns="http://www.w3.org/2000/svg">
                            <path
                                d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456l-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
                            <path fill-rule="evenodd"
                                d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z" />
                        </svg></a> |
                    <a href="{% url 'todo:delete' item.id %}"
                        style="padding-right:15px;padding-left:15px; color:red;"><svg width="1em" height="1em"
                            viewBox="0 0 16 16" class="bi bi-x-circle" fill="currentColor"
                            xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd"
                                d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
                            <path fill-rule="evenodd"
                                d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z" />
                        </svg></a>
                </div>
            </div>
            <br>
            {% endif %}
            {% endfor %}
            {% endif %}
    </div>
    <div class="container">
        <h2>Done List</h2>
        {% if task_list %}
        </ul>
        <ul id="list2">
            {% for item in task_list reversed %}
            {% if item.done == True %}
            <div id=line2
                style=" display: flex;width: 85%;  font-size: 18px; border-color: rgb(12, 11, 11); border-width: 1px;border-style: solid; ">
                <div style="float: left;width: 80%;padding-right:30px;padding-left:30px;">
                    <a href="#" onclick="favPost('{% url 'todo:toggle' item.id %}', );return false;"
                        style="padding-right:30px;padding-left:30px;"><svg width="1em" height="1em" viewBox="0 0 16 16"
                            class="bi bi-check-circle-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd"
                                d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z" />
                        </svg></a>
                    {{ item.task }}
                </div>
                <div>
                    <a href="{% url 'todo:update' item.id %}"
                        style="padding-right:15px;padding-left:15px; color: turquoise;"><svg width="1em" height="1em"
                            viewBox="0 0 16 16" class="bi bi-pencil-square" fill="currentColor"
                            xmlns="http://www.w3.org/2000/svg">
                            <path
                                d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456l-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
                            <path fill-rule="evenodd"
                                d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z" />
                        </svg></a> |
                    <a href="{% url 'todo:delete' item.id %}"
                        style="padding-right:15px;padding-left:15px; color:red"><svg width="1em" height="1em"
                            viewBox="0 0 16 16" class="bi bi-x-circle" fill="currentColor"
                            xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd"
                                d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
                            <path fill-rule="evenodd"
                                d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z" />
                        </svg></a>
                </div>
            </div>
            <br>
            {% endif %}
            {% endfor %}


        </ul>


        {% else %}
        <div>There are no tasks todo.</div>

        {% endif %}
        <h4><a onclick="myFunction()">Add a task <svg width="1em" height="1em" viewBox="0 0 16 16"
                    class="bi bi-plus-circle" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd"
                        d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
                    <path fill-rule="evenodd"
                        d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z" />
                </svg></a></h4>

        <div id="myDIV" class="form-group">
            <form id="myForm">
                <p>Task:</p>
                <input type="text" class="form-control" name="task" placeholder="Enter task">
                <br><br>
                <p>dec</p>
                <input type="text" class="form-control" name="dec" placeholder="Enter desc">
                <br>
            </form>
            <button onclick="Submitform()" class="btn btn-secondary">GO</button>
        </div>
    </div>
    {% else %}
    <div class="container" sytle="width:100%">
        <div style="padding-right:20%;padding-left:30%;padding-top:2% ">
            <h3>Please login to continue</h3>
        </div>
    </div>
    {% endif %}
</body>
{% endblock %}

tms/todo/templates/todo/task_update.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<style>
    body {
        background: url("{% static 'todo/edit.jpg' %}") no-repeat center center fixed;
        background-size: cover;

        /* background-image: url("{% static 'todo/list.jpg' %}");
        background-repeat: no-repeat; */
    }
</style>
<div class="continer">

    <form method="POST">
        {% csrf_token %}
        <br>
        <h1>Edit Task</h1>
        <hr>
        <p>Task</p>
        <input type="text" class="form-control" name="task" value="{{task}}">
        <br>
        <p>Content</p>
        <textarea class="form-control" name="desc">{{desc}} </textarea>
        <br>
        <button type="submit" class="btn btn-success">Save Changes</button>
        <input type="submit" onclick="window.location='{% url 'todo:items' %}' ; return false;" value="Cancel">
    </form>
</div>
{% endblock %}